### ISSUE TITLE
实验二有一些小问题

### ISSUE THREAD

**Issue by shao639** [fetschs/HIT-20Spring-IR-Lab#1]
同学你好 我实验2有一些小问题想要咨询你 可以把你的邮箱 发给我吗 我上github随缘 很难受

**Comment by fetschs** [comment]
> 同学你好 我实验2有一些小问题想要咨询你 可以把你的邮箱 发给我吗 我上github随缘 很难受

个人主页里有 fetschs@foxmail.com
